# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-23 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('operation_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('operation_name', models.CharField(max_length=30, unique=True)),
                ('operation_value', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'operations',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('rule_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('rule_name', models.CharField(max_length=30)),
                ('signal', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('value_type', models.CharField(max_length=30)),
                ('criteria', models.ForeignKey(db_column='criteria', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.Operations', to_field='operation_name')),
            ],
            options={
                'db_table': 'rules',
            },
        ),
    ]
